pool:
  vmImage: 'ubuntu-18.04'
trigger: 
  - master
steps:
- task: CopyFiles@2
  displayName: 'Copy files to:$(build.artifactstagingdirectory)/Templates '
  inputs:
    SourceFolder: 'deployment'
    Contents: '*.json'
    TargetFolder: '$(build.artifactstagingdirectory)/Templates'
- task: Npm@1
  displayName: 'npm custome'
  inputs:
    command: 'custom'
    verbose: false
    customCommand: 'install --production'
- task: ArchiveFiles@2
  displayName: 'Archive $(Build.SourceDirectory)'
  inputs:
    rootFolderOrFile: '$(Build.SourceDirectory)'
    includeRootFolder: false
- task: PublishBuildArtifacts@1
  displayName: 'publish artificat : drop'
